# Generated by Django 5.0.1 on 2024-02-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_number', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=5)),
                ('batch_name', models.CharField(max_length=3)),
            ],
        ),
    ]
